export const LOADING_START = "LOADING_START";
export const LOADING_STOP = "LOADING_STOP";

export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";

export const FETCH_ALL_SCENARIOS = "FETCH_ALL_SCENARIOS";
export const FETCH_SCENARIO_DETAIL = "FETCH_SCENARIO_DETAIL";
export const FETCH_SCENARIO_TALK = "FETCH_SCENARIO_TALK";
export const CREATE_SCENARIO_TALK = "CREATE_SCENARIO_TALK";
export const UPLOAD_IMPORT_FILE = "UPLOAD_IMPORT_FILE";
export const UPLOAD_CSV_FILE = "UPLOAD_CSV_FILE";
export const UPLOAD_LOCATION_CSV_FILE = "UPLOAD_LOCATION_CSV_FILE";
export const DOWNLOAD_CSV_FILE = "DOWNLOAD_CSV_FILE";
export const DOWNLOAD_EXPORT_FILE = "DOWNLOAD_EXPORT_FILE";
export const CHANGE_ACTIVE_SCENARIO = "CHANGE_ACTIVE_SCENARIO";
export const UPDATE_TEXT_MAPPING = "UPDATE_TEXT_MAPPING";
export const UPDATE_SCENARIO_DATA = "UPDATE_SCENARIO_DATA";
export const UPDATE_TALK_UPDATED_TIME = "UPDATE_TALK_UPDATED_TIME";
export const DELETE_SCENARIO_VERSION = "DELETE_SCENARIO_VERSION";
export const CREATE_SCENARIO_VERSION = "CREATE_SCENARIO_VERSION";
export const ADD_COMPOSITE_MESSAGE = "ADD_COMPOSITE_MESSAGE";
export const FETCH_ACTIVE_SCENARIO_DATA = "FETCH_ACTIVE_SCENARIO_DATA";
export const CREATE_SIMPLE_SPECIAL_SCENARIO = "CREATE_SIMPLE_SPECIAL_SCENARIO";
export const SET_DEFAULT_RICH_MENU = "SET_DEFAULT_RICH_MENU";
export const DELETE_TALK = "DELETE_TALK";
export const DELETE_SPECIAL_SCENARIO = "DELETE_SPECIAL_SCENARIO";
export const SAVE_ACTIVE_SCENARIO = "SAVE_ACTIVE_SCENARIO";
export const DELETE_SCENARIO_MESSAGE = "DELETE_SCENARIO_MESSAGE";
export const FETCH_SCENARIO_DETAIL_TALK = "FETCH_SCENARIO_DETAIL_TALK";

export const CREATE_RICH_MENU = "CREATE_RICH_MENU";
export const COPY_RICH_MENU = "COPY_RICH_MENU";
export const DELETE_RICH_MENU = "DELETE_RICH_MENU";

export const FETCH_ACTIVE_RICHMENUS = "FETCH_ACTIVE_RICHMENUS";
export const FETCH_ALL_RICHMENUS = "FETCH_ALL_RICHMENUS";
export const FETCH_DEFAULT_RICHMENUS = "FETCH_DEFAULT_RICHMENUS";
export const SET_ACTIVE_RICH_MENU = "SET_ACTIVE_RICH_MENU";
export const TOGGLE_BOSAI_MODE = "TOGGLE_BOSAI_MODE";
export const SAVE_BOSAI_SETTINGS_ITEM = "SAVE_BOSAI_SETTINGS_ITEM";
export const GET_ZIP_CODES = "GET_ZIP_CODES";
export const DELETE_ZIP_CODES = "DELETE_ZIP_CODES";
export const DOWNLOAD_ZIP_CSV = "DOWNLOAD_ZIP_CSV";
export const FETCH_SPECIAL_TALK_FLOW_START = "FETCH_SPECIAL_TALK_FLOW_START";
export const FETCH_ALL_RICHMENUS_ALIAS_LIST = "FETCH_ALL_RICHMENUS_ALIAS_LIST";

export const SAVE_TALK_NODES = "SAVE_TALK_NODES";

export const FETCH_SCENARIO_SPECIFIC_TALKS = "FETCH_SCENARIO_SPECIFIC_TALKS";
export const UPDATE_SCENARIO_TALK_NAME = "UPDATE_SCENARIO_TALK_NAME";
export const UPDATE_DISPLAY_SCENARIO_VERSION_NAME = "UPDATE_DISPLAY_SCENARIO_VERSION_NAME";

export const AGGREGATE_TALK_LOG = "AGGREGATE_TALK_LOG";
export const FETCH_TALK_LOG_LISTS = "FETCH_TALK_LOG_LISTS";

// segment actions
export const FETCH_ALL_SEGMENT_DELIVERIES = "FETCH_ALL_SEGMENT_DELIVERIES";
export const CREATE_SEGMENT_DELIVERY = "CREATE_SEGMENT_DELIVERY";
export const UPDATE_SEGMENT_DELIVERY = "UPDATE_SEGMENT_DELIVERY";
export const DELETE_SEGMENT_DELIVERY = "DELETE_SEGMENT_DELIVERY";

export const FETCH_MAIL_DELIVERY_LIST = "FETCH_MAIL_DELIVERY_LIST";
export const FETCH_TALK_DELIVERY_LIST = "FETCH_TALK_DELIVERY_LIST";
