// scenario

export const FETCH_SCENARIOS_SETTING = "FETCH_SCENARIOS_SETTING"
export const FETCH_SCENARIOS_LIST = "FETCH_SCENARIOS_LIST"
export const SET_SETTING_SCENARIOS = "SET_SETTING_SCENARIOS"
export const SET_TABLE_OPTION_SCENARIO = "SET_TABLE_OPTION_SCENARIO"
export const SET_SEARCH_ATTRIBUTE_SCENARIO = "SET_SEARCH_ATTRIBUTE_SCENARIO"
export const SET_SEARCH_KEYWORD_SCENARIO = "SET_SEARCH_KEYWORD_SCENARIO"
export const SET_LIST_SCENARIOS = "SET_LIST_SCENARIOS"
export const SET_SCENARIOS_TALK_PAGINATE = "SET_SCENARIOS_TALK_PAGINATE"
