export default {
  scenariosList: {},
  isFetchingScenarios: false,
  fetchScenariosError: null,
  selectedScenario: {},
  activeScenarioData: {},
  activeScenario: {},
  isFetchingScenarioDetail: false,
  totalTalks: 0,
  talkDataTableOptions: {
    groupBy: [],
    groupDesc: [],
    itemsPerPage: 10,
    multiSort:false,
    mustSort:false,
    page: 1,
    sortBy: ["updated_at"],
    sortDesc: [true],
  },
  searchTalkAttribute: null,
  searchTalkKeyword: null,
  searchTalkStartDate: null,
  searchTalkEndDate: null,
  fetchScenarioDetailError: null,
  isImportingScenarioData: false,
  importingScenarioDataError: null,
  importingScenarioDataWarning: null,
  isExportingScenarioData: false,
  exportingScenarioDataError: null,
  exportingScenarioDataWarning: null,
  exportFinishSuccess: false,
  importFinishSuccess: false,
  createFinishSuccess: false,
  scenarioMessages: [],
  scenarioMindmap: {
    specialTalkRootNodes: {},
    cachedSpecialTalkFlow: {},
    specialTalkFirstBotReply: {},
  },
  scenarioTextmap: {},
  scenarioTalks: [],
  deleteScenarioTalkSuccess: null,
  isDeletingScenarioVersion: false,
  deletingScenarioVersionError: null,
  deleteFinishSuccess: false,
  displayMessages: [],
  userMessages: {},
  selectedEditScenario: {
    production: null,
    sandbox: null,
  },
  isSavingActiveScenario: false,
  isCreatingRichMenu: false,
  isCreatingRichMenuError: null,
  isFetchingRichMenu: false,
  isFetchingRichMenuError: null,
  richMenus: [],

  isDeletingRichMenu: false,
  errorDeletingRichMenu: null,

  defaultProductionRichMenu: null,
  defaultSandboxRichMenu: null,
  bosaiProductionRichMenu: null,
  bosaiSandboxRichMenu: null,
  activeProductionRichMenu: null,
  activeSandboxRichMenu: null,
  productionRichMenuList: [],
  sandboxRichMenuList: [],

  errorFetchingRichMenuInfo: null,
  isFetchingRichMenuInfo: false,

  isFetchingAllRichMenus: false,
  errorFetchingAllRichMenus: null,

  errorSettingRichMenu: null,
  isSettingScenarioRichMenu: false,

  scenarioInBosaiMode: {
    production: false,
    sandbox: false,
  },
  settingBosaiSettingsSuccess: false,
  isFetchingZipCodes: false,
  fetchZipCodeError: null,
  zipCodes: {},

  isSavingTalkNodes: false,
  saveTalkNodesError: null,
  saveTalkNodesSuccess: false,

  isChangingTalkName: false,
  changingTalkNameError: null,

  agregateTalkLog: null,
  agregateTalkLogError: null,
  isFetchingTalkLogLists: null,
  isFetchingTalkLogListsError: null,
  isChangingVersionName: false,
  changingVersionNameError: false,
  scenariosListPaginate: [],
  scenarioTalksPaginate: [],
  dataTableOptions: {
    sortBy: "type",
    sortType: 'desc',
    page: 1,
    perPage: 10
  },
  settings: {},
  searchAttribute: "",
  searchKeyword: ""
};
